baseURL: https://turitoyuenan.github.io/KnabinoMagia/
languageCode: en-us

title: Knabino Magia
params:
  author: Turito Yuenan
  description: Magical girl Fiction

menu:
  main:
    - name: Magical girls
      url: /magical-girls/
      weight: 550
    - name: Countries
      url: /countries/
      weight: 456
    - name: Extras
      url: /extras/
      weight: 789
